# create subsets of fonts for my website
name: extrafonts

on:
  workflow_dispatch:

jobs:
  enable:
    runs-on: ubuntu-latest

    name: Create fonts

    steps:
      - uses: actions/checkout@HEAD

      - name: Checkout chars
        uses: actions/checkout@HEAD
        with:
          path: chars
          repository: chuxinyuan/chars
          submodules: recursive

      - name: Install packages
        run: |
          sudo apt-get -qq install -y fonttools > /dev/null

      - name: Extract characters
        run: |
          mkdir -p fonts
          find chars -name '*.md' -exec grep -o -P '[\x{4E00}-\x{9FFF}]' {} \; | sort | uniq > fonts/extra_chars.txt

      - name: Build fonts
        run: |
          export FONT_NAME=FZKTK
          wget -nv https://raw.githubusercontent.com/Universebenzene/wps-office-fonts/master/${FONT_NAME}.TTF -O ${FONT_NAME}.TTF
          pyftsubset ${FONT_NAME}.TTF --text-file=fonts/extra_chars.txt --no-hinting --flavor=woff2 --output-file=fonts/Extra-${FONT_NAME}-cxy.woff2

      - name: Push fonts
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add fonts/*
          git commit -m "update fonts" && git push || true
